import fs   from 'fs'
import path from 'path'
import Link from 'next/link'
import { getArticleBySlug, getAllSlugs, isoDate, getSeriesEpisodes, imageDimensions } from '@/lib/articles'
import { SERIES, type SeriesKey } from '@/lib/series'
import { arabicDigits } from '@/lib/digits'
import SeriesTrack from '@/components/SeriesTrack'
import ArticleEnd  from '@/components/ArticleEnd'
import Gallery from '@/components/Gallery'
import { BLOG_CONFIG } from '@/lib/config'
import type { Metadata } from 'next'

interface Props {
  params: { slug: string }
}

// ── Pre-generate all article pages at build time ─────────────────────────
export async function generateStaticParams() {
  return getAllSlugs().map(slug => ({ slug }))
}

// ── Share image ──────────────────────────────────────────────────────────
// Prefer the article's own cover, then a per-article OG card generated by
// `npm run og`, then the site default. The per-article card is only used when
// the file is actually on disk — a missing one would otherwise 404 in scrapers.
function shareImage(slug: string, cover?: string): string {
  if (cover) return cover
  const perArticle = path.join(process.cwd(), 'public', 'og', `${slug}.jpg`)
  return fs.existsSync(perArticle) ? `/og/${slug}.jpg` : '/og/default.jpg'
}

// ── Page metadata ────────────────────────────────────────────────────────
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const article = await getArticleBySlug(params.slug)
  const { meta, slug } = article
  const url   = `/articles/${slug}/`
  const image = shareImage(slug, meta.cover)

  return {
    // The layout template appends « — مصطفى فؤاد ».
    title:       meta.title,
    description: meta.excerpt,
    alternates:  { canonical: url },
    openGraph: {
      type:          'article',
      locale:        'ar_SA',
      url,
      siteName:      BLOG_CONFIG.blogName,
      title:         meta.title,
      description:   meta.excerpt,
      publishedTime: isoDate(meta.date),
      images:        [{ url: image, width: 1200, height: 630 }],
    },
    twitter: {
      card:        'summary_large_image',
      title:       meta.title,
      description: meta.excerpt,
      images:      [image],
    },
  }
}

// ── Article page ──────────────────────────────────────────────────────────
export default async function ArticlePage({ params }: Props) {
  const article = await getArticleBySlug(params.slug)
  const { slug, meta, contentHtml } = article

  // ── JSON-LD: Article ────────────────────────────────────────────────
  const articleLd = {
    '@context':        'https://schema.org',
    '@type':           'Article',
    headline:          meta.title,
    description:       meta.excerpt,
    datePublished:     isoDate(meta.date),
    inLanguage:        'ar',
    image:             `${BLOG_CONFIG.siteUrl}${shareImage(slug, meta.cover)}`,
    mainEntityOfPage:  `${BLOG_CONFIG.siteUrl}/articles/${slug}/`,
    author: {
      '@type': 'Person',
      name:    BLOG_CONFIG.siteTitle,
      url:     BLOG_CONFIG.linkedin,
    },
  }

  // ── Series bar (only for articles that belong to a series) ──────────
  const seriesKey   = meta.series as SeriesKey | undefined
  const seriesEntry = seriesKey ? SERIES[seriesKey] : undefined
  const episodes    = seriesEntry ? getSeriesEpisodes(seriesKey!) : []

  // Reserve the box for the cover and every carousel slide before they load.
  const coverDim = meta.cover ? imageDimensions(meta.cover) : null
  const gallery  = meta.gallery?.map(item => ({
    ...item,
    ...(imageDimensions(item.image) ?? {}),
  }))

  return (
    <article className="reading">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleLd) }}
      />

      <Link href="/" className="back">
        <span>→</span><span>كل المقالات</span>
      </Link>

      {seriesEntry && (
        <div className="series-bar">
          <Link href={`/series/${seriesKey}/`} className="series-bar-title">
            {seriesEntry.title}
          </Link>
          <SeriesTrack total={seriesEntry.total} episodes={episodes} currentSlug={slug} />
          <span className="series-bar-count">
            الحلقة {arabicDigits(meta.episode as number)} من {arabicDigits(seriesEntry.total)}
          </span>
        </div>
      )}

      <header className="art-head">
        <div className="meta">
          <span className="chip">{meta.tag}</span>
          <span className="date">{meta.date_ar}</span>
          {meta.readTime && (
            <>
              <span className="dot" />
              <span className="date">{meta.readTime} للقراءة</span>
            </>
          )}
        </div>
        <h1>{meta.title}</h1>
        {meta.subtitle && <p className="sub">{meta.subtitle}</p>}
      </header>

      {meta.cover && (
        <img
          className="art-cover"
          src={meta.cover}
          alt={meta.title}
          width={coverDim?.width}
          height={coverDim?.height}
          loading="eager"
          fetchPriority="high"
          decoding="async"
        />
      )}

      {gallery && gallery.length > 0 && (
        <Gallery items={gallery} alt={meta.title} />
      )}

      <div
        className="article-content"
        dangerouslySetInnerHTML={{ __html: contentHtml }}
      />

      <p className="art-foot">✦ <span className="road">يتبع</span> ✦</p>

      <ArticleEnd slug={slug} />

      <Link href="/" className="back">
        <span>→</span><span>عودة للمقالات</span>
      </Link>
    </article>
  )
}
